parameters:
#    tipddy_oms.example.class: Tipddy\OMSBundle\Example

services:
#    tipddy_oms.example:
#        class: %tipddy_oms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
